using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web;

namespace ProyectoPrograWebHHK.Models
{
    public static class Email
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Desechar (Dispose) objetos antes de perder el ámbito", Justification = "<pendiente>")]
        public static bool SendEmail(string to, string body, string subject)
        {
            var email = new MailMessage
            {
                From = new MailAddress("hhkmotorcycles@gmail.com"),
                Subject = subject,
                Body = body,
                IsBodyHtml = true,
                Priority = MailPriority.Normal,
            };
            email.To.Add(new MailAddress(to));
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587;
            smtp.EnableSsl = true;
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new NetworkCredential("hhkmotorcycles@gmail.com", "HhkMotor!1");
            try
            {
                smtp.Send(email);
                email.Dispose();
                return true;
            }
            catch (Exception e)
            {
                return false;
            }
        }

        public static string BuildWelcomeBody()
        {
            StringBuilder builder = new StringBuilder();

            builder.Append("<!DOCTYPE html PUBLIC >																																												 ");
            builder.Append("<html xmlns=\"http://www.w3.org/1999/xhtml\">																																																																	 ");
            builder.Append("<head>																																																																										 ");
            builder.Append("  <meta http-equiv=\"Content - Type\" content=\"text / html; charset = UTF - 8\" />																																																										 ");
            builder.Append("  <meta name=\"viewport\" content=\"width = device - width, initial - scale = 1\" />																																																									 ");
            builder.Append("  <title>Neopolitan Welcome Email</title>																																																																	 ");
            builder.Append("  <!-- Designed by https://github.com/kaytcat -->																																																															 ");
            builder.Append("  <!-- Robot header image designed by Freepik.com -->																																																														 ");
            builder.Append("																																																																											 ");
            builder.Append("  <style type=\"text / css\">																																																																					 ");
            builder.Append("  @import url(http://fonts.googleapis.com/css?family=Droid+Sans);																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append("  /* Take care of image borders and formatting */																																																															 ");
            builder.Append("																																																																											 ");
            builder.Append("  img {																																																																										 ");
            builder.Append("    max-width: 600px;																																																																						 ");
            builder.Append("    outline: none;																																																																							 ");
            builder.Append("    text-decoration: none;																																																																					 ");
            builder.Append("    -ms-interpolation-mode: bicubic;																																																																		 ");
            builder.Append("  }																																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append("  a {																																																																										 ");
            builder.Append("    text-decoration: none;																																																																					 ");
            builder.Append("    border: 0;																																																																								 ");
            builder.Append("    outline: none;																																																																							 ");
            builder.Append("    color: #bbbbbb;																																																																							 ");
            builder.Append("  }																																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append("  a img {																																																																									 ");
            builder.Append("    border: none;																																																																							 ");
            builder.Append("  }																																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append("  /* General styling */																																																																						 ");
            builder.Append("																																																																											 ");
            builder.Append("  td, h1, h2, h3  {																																																																							 ");
            builder.Append("    font-family: Helvetica, Arial, sans-serif;																																																																 ");
            builder.Append("    font-weight: 400;																																																																						 ");
            builder.Append("  }																																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append("  td {																																																																										 ");
            builder.Append("    text-align: center;																																																																						 ");
            builder.Append("  }																																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append("  body {																																																																									 ");
            builder.Append("    -webkit-font-smoothing:antialiased;																																																																		 ");
            builder.Append("    -webkit-text-size-adjust:none;																																																																			 ");
            builder.Append("    width: 100%;																																																																							 ");
            builder.Append("    height: 100%;																																																																							 ");
            builder.Append("    color: #37302d;																																																																							 ");
            builder.Append("    background: #ffffff;																																																																					 ");
            builder.Append("    font-size: 16px;																																																																						 ");
            builder.Append("  }																																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append("   table {																																																																									 ");
            builder.Append("    border-collapse: collapse !important;																																																																	 ");
            builder.Append("  }																																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append("  .headline {																																																																								 ");
            builder.Append("    color: #ffffff;																																																																							 ");
            builder.Append("    font-size: 36px;																																																																						 ");
            builder.Append("  }																																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append(" .force-full-width {																																																																						 ");
            builder.Append("  width: 100% !important;																																																																					 ");
            builder.Append(" }																																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append("  </style>																																																																									 ");
            builder.Append("																																																																											 ");
            builder.Append("  <style type=\"text / css\" media=\"screen\">																																																																	 ");
            builder.Append("      @media screen {																																																																						 ");
            builder.Append("         /*Thanks Outlook 2013! http://goo.gl/XLxpyl*/																																																														 ");
            builder.Append("        td, h1, h2, h3 {																																																																					 ");
            builder.Append("          font-family: 'Droid Sans', 'Helvetica Neue', 'Arial', 'sans-serif' !important;																																																					 ");
            builder.Append("        }																																																																									 ");
            builder.Append("      }																																																																										 ");
            builder.Append("  </style>																																																																									 ");
            builder.Append("																																																																											 ");
            builder.Append("  <style type=\"text / css\" media=\"only screen and(max - width: 480px)\">																																																										 ");
            builder.Append("    /* Mobile styles */																																																																						 ");
            builder.Append("    @media only screen and (max-width: 480px) {																																																																 ");
            builder.Append("																																																																											 ");
            builder.Append("      table[class=\"w320\"] {																																																																					 ");
            builder.Append("        width: 320px !important;																																																																			 ");
            builder.Append("      }																																																																										 ");
            builder.Append("																																																																											 ");
            builder.Append("																																																																											 ");
            builder.Append("    }																																																																										 ");
            builder.Append("  </style>																																																																									 ");
            builder.Append("</head>																																																																										 ");
            builder.Append("<body class=\"body\" style=\"padding: 0; margin: 0; display: block; background:#ffffff; -webkit-text-size-adjust:none\" bgcolor=\"#ffffff\">																																											 ");
            builder.Append("<table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" width=\"100 % \" height=\"100 % \" >																																																							 ");
            builder.Append("  <tr>																																																																										 ");
            builder.Append("    <td align=\"center\" valign=\"top\" bgcolor=\"#ffffff\"  width=\"100%\">																																																										 ");
            builder.Append("      <center>																																																																								 ");
            builder.Append("        <table style=\"margin: 0 auto; \" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"w320\">																																																			 ");
            builder.Append("          <tr>																																																																								 ");
            builder.Append("            <td align=\"center\" valign=\"top\" > ");
            builder.Append("																																																																											 ");
            builder.Append("                <table style=\"margin: 0 auto; \" cellpadding=\"0\" cellspacing=\"0\" width=\"100 % \" style=\"margin: 0 auto; \">																																															 ");
            builder.Append("                  <tr>																																																																						 ");
            builder.Append("                    <td style=\"font - size: 30px; text - align:center; \">																																																										 ");
            builder.Append("                      <br>																																																																					 ");
            builder.Append("                        HHK Motorcycles!																																																																		 ");
            builder.Append("                      <br>																																																																					 ");
            builder.Append("                      <br>																																																																					 ");
            builder.Append("                    </td>																																																																					 ");
            builder.Append("                  </tr>																																																																						 ");
            builder.Append("                </table>																																																																					 ");
            builder.Append("																																																																											 ");
            builder.Append("                <table style=\"margin: 0 auto; \" cellpadding =\"0\" cellspacing =\"0\" width =\"100 % \" bgcolor =\"#4dbfbf\" > ");
            builder.Append("                  <tr>																																																																						 ");
            builder.Append("                    <td>																																																																					 ");
            builder.Append("                    <br>																																																																					 ");
            builder.Append("                      <img src=\"https://www.filepicker.io/api/file/Pv8CShvQHeBXdhYu9aQE \" width =\"216\" height =\"189\" alt =\"robot picture\" > ");
            builder.Append("                    </td>																																																																					 ");
            builder.Append("                  </tr>																																																																						 ");
            builder.Append("                  <tr>																																																																						 ");
            builder.Append("                    <td class=\"headline\" > ");
            builder.Append("                      Welcome!																																																																				 ");
            builder.Append("                    </td>																																																																					 ");
            builder.Append("                  </tr>																																																																						 ");
            builder.Append("                  <tr>																																																																						 ");
            builder.Append("                    <td>																																																																					 ");
            builder.Append("																																																																											 ");
            builder.Append("                      <center>																																																																				 ");
            builder.Append("                        <table style=\"margin: 0 auto;\" cellpadding =\"0\" cellspacing =\"0\" width =\"60 % \" > ");
            builder.Append("                          <tr>																																																																				 ");
            builder.Append("                            <td style=\"color:#187272;\" > ");
            builder.Append("                            <br>																																																																			 ");
            builder.Append("                             Bienvenido a esta gran comunidad de motociclistas, en nuestra tienda encontraras grandes ofertas en refacciones.																																														 ");
            builder.Append("                            <br>																																																																			 ");
            builder.Append("                            <br>																																																																			 ");
            builder.Append("                            </td>																																																																			 ");
            builder.Append("                          </tr>																																																																				 ");
            builder.Append("                        </table>																																																																			 ");
            builder.Append("                      </center>																																																																				 ");
            builder.Append("																																																																											 ");
            builder.Append("                    </td>																																																																					 ");
            builder.Append("                  </tr>																																																																						 ");
            builder.Append("                  <tr>																																																																						 ");
            builder.Append("                    <td>																																																																					 ");
            builder.Append("                        <v:roundrect xmlns:v=\"urn: schemas - microsoft - com:vml\" xmlns: w =\"urn: schemas - microsoft - com:office: word\" href =\"http://\" style =\"height:50px;v-text-anchor:middle;width:200px;\" arcsize =\"8%\" stroke =\"f\" fillcolor =\"#178f8f\" > ");
            builder.Append("                          <w:anchorlock/>																																																																	 ");
            builder.Append("                      <br>																																																																					 ");
            builder.Append("                    </td>																																																																					 ");
            builder.Append("                  </tr>																																																																						 ");
            builder.Append("                </table>																																																																					 ");
            builder.Append("																																																																											 ");
            builder.Append("                <table style=\"margin: 0 auto;\" cellpadding =\"0\" cellspacing =\"0\" width =\"100 % \" bgcolor =\"#f5774e\" > ");
            builder.Append("                  <tr>																																																																						 ");
            builder.Append("                      <br>																																																																					 ");
            builder.Append("                      <br>																																																																					 ");
            builder.Append("                     Las mejores Marcas, solo para ti!																																																																		 ");
            builder.Append("                    </td>																																																																					 ");
            builder.Append("                  </tr>																																																																						 ");
            builder.Append("                  <tr>																																																																						 ");
            builder.Append("                    <td>																																																																					 ");
            builder.Append("                      <img src=\"https://www.filepicker.io/api/file/tjUsYjIHSDCkrrniLuev\" width =\"145\" height =\"89\" alt =\"meter image\" > ");
            builder.Append("                    </td>																																																																					 ");
            builder.Append("                  </tr>																																																																						 ");
            builder.Append("                  <tr>																																																																						 ");
            builder.Append("                    <td>																																																																					 ");
            builder.Append("																																																																											 ");
            builder.Append("                      <center>																																																																				 ");
            builder.Append("                        <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" width=\"60 % \" > ");
            builder.Append("                          <tr>																																																																				 ");
            builder.Append("                            <td style=\"color:#933f24;\" > ");
            builder.Append("                            <br>																																																																			 ");
            builder.Append("                              Las motos mas veloces para nuestros clientes																																																											 ");
            builder.Append("                              si requieres alguna motocicleta que no este en nuestro catalogo  te la conseguimos																																																								 ");
            builder.Append("                              <br><br>																																																																		 ");
            builder.Append("                            </td>																																																																			 ");
            builder.Append("                          </tr>																																																																				 ");
            builder.Append("                        </table>																																																																			 ");
            builder.Append("                      </center>																																																																				 ");
            builder.Append("																																																																											 ");
            builder.Append("                    </td>																																																																					 ");
            builder.Append("                  </tr>																																																																						 ");
            builder.Append("                  <tr>																																																																						 ");
            builder.Append("                    <td>																																																																					 ");
            builder.Append("                      <br>																																																																					 ");
            builder.Append("                      <br>																																																																					 ");
            builder.Append("                    </td>																																																																					 ");
            builder.Append("                  </tr>																																																																						 ");
            builder.Append("                </table>																																																																					 ");
            builder.Append("                <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" class=\"force - full - width\" bgcolor =\"#414141\" style =\"margin: 0 auto\" > ");
            builder.Append("                  <tr>																																																																						 ");
            builder.Append("                    <td style=\"background - color:#414141;\" > ");
            builder.Append("                    <br>																																																																					 ");
            builder.Append("                    <br>																																																																					 ");
            builder.Append("                      <img src=\"https://www.filepicker.io/api/file/R4VBTe2UQeGdAlM7KDc4\" alt =\"google+\" > ");
            builder.Append("                      <img src=\"https://www.filepicker.io/api/file/cvmSPOdlRaWQZnKFnBGt\" alt =\"facebook\" > ");
            builder.Append("                      <img src=\"https://www.filepicker.io/api/file/Gvu32apSQDqLMb40pvYe\" alt =\"twitter\" > ");
            builder.Append("                      <br>																																																																					 ");
            builder.Append("                      <br>																																																																					 ");
            builder.Append("                    </td>																																																																					 ");
            builder.Append("                  </tr>																																																																						 ");
            builder.Append("                  <tr>																																																																						 ");
            builder.Append("                    <td style=\"color:#bbbbbb; font-size:12px;\" > ");
            builder.Append("                      siguenos en nuestras redes sociales");
            builder.Append("                      <br><br>																																																																				 ");
            builder.Append("                    </td>																																																																					 ");
            builder.Append("                  </tr>																																																																						 ");
            builder.Append("                  <tr>																																																																						 ");
            builder.Append("                    <td style=\"color:#bbbbbb; font-size:12px;\" > ");
            builder.Append("                       © 2019 Antonio contreras universidad UCAD																																																															 ");
            builder.Append("                       <br>																																																																					 ");
            builder.Append("                       <br>																																																																					 ");
            builder.Append("                    </td>																																																																					 ");
            builder.Append("                  </tr>																																																																						 ");
            builder.Append("                </table>																																																																					 ");
            builder.Append("            </td>																																																																							 ");
            builder.Append("          </tr>																																																																								 ");
            builder.Append("        </table>																																																																							 ");
            builder.Append("    </center>																																																																								 ");
            builder.Append("    </td>																																																																									 ");
            builder.Append("  </tr>																																																																										 ");
            builder.Append("</table>																																																																									 ");
            builder.Append("</body>																																																																										 ");
            builder.Append("</html>																																																																										 ");

            return builder.ToString();
        }

        public static string BuildBuyBody(List<CarritoCompras> carrito, Venta venta, Cliente cliente)
        {
            var builder = new StringBuilder();


            builder.Append("<!DOCTYPE html PUBLIC \" -//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd \">																																											   ");
            builder.Append("<html xmlns=\"http://www.w3.org/1999/xhtml \" > ");
            builder.Append("<head>																																																																								   ");
            builder.Append("  <meta http-equiv=\"Content-Type\" content =\"text/html; charset=UTF-8\" />																																																							   ");
            builder.Append("  <meta name=\"viewport\" content =\"width=device-width, initial-scale=1\" />																																																							   ");
            builder.Append("  <title>Neopolitan Invoice Email</title>																																																															   ");
            builder.Append("  <!-- Designed by https://github.com/kaytcat -->																																																													   ");
            builder.Append("  <!-- Robot header image designed by Freepik.com -->																																																												   ");
            builder.Append("																																																																									   ");
            builder.Append("  <style type=\"text/css\">																																																																			   ");
            builder.Append("  @import url(http://fonts.googleapis.com/css?family=Droid+Sans);																																																									   ");
            builder.Append("																																																																									   ");
            builder.Append("  /* Take care of image borders and formatting */																																																													   ");
            builder.Append("																																																																									   ");
            builder.Append("  img {																																																																							   ");
            builder.Append("    max-width: 600px;																																																																				   ");
            builder.Append("    outline: none;																																																																					   ");
            builder.Append("    text-decoration: none;																																																																			   ");
            builder.Append("    -ms-interpolation-mode: bicubic;																																																																   ");
            builder.Append("  }																																																																								   ");
            builder.Append("																																																																									   ");
            builder.Append("  a {																																																																								   ");
            builder.Append("    text-decoration: none;																																																																			   ");
            builder.Append("    border: 0;																																																																						   ");
            builder.Append("    outline: none;																																																																					   ");
            builder.Append("    color: #bbbbbb;																																																																				   ");
            builder.Append("  }																																																																								   ");
            builder.Append("																																																																									   ");
            builder.Append("  a img {																																																																							   ");
            builder.Append("    border: none;																																																																					   ");
            builder.Append("  }																																																																								   ");
            builder.Append("																																																																									   ");
            builder.Append("  /* General styling */																																																																			   ");
            builder.Append("																																																																									   ");
            builder.Append("  td, h1, h2, h3  {																																																																				   ");
            builder.Append("    font-family: Helvetica, Arial, sans-serif;																																																														   ");
            builder.Append("    font-weight: 400;																																																																				   ");
            builder.Append("  }																																																																								   ");
            builder.Append("																																																																									   ");
            builder.Append("  td {																																																																								   ");
            builder.Append("    text-align: center;																																																																			   ");
            builder.Append("  }																																																																								   ");
            builder.Append("																																																																									   ");
            builder.Append("  body {																																																																							   ");
            builder.Append("    -webkit-font-smoothing:antialiased;																																																															   ");
            builder.Append("    width: 100%;																																																																					   ");
            builder.Append("    height: 100%;																																																																					   ");
            builder.Append("    -webkit-text-size-adjust:none;																																																																	   ");
            builder.Append("    color: #37302d;																																																																				   ");
            builder.Append("    background: #ffffff;																																																																			   ");
            builder.Append("    font-size: 16px;																																																																				   ");
            builder.Append("  }																																																																								   ");
            builder.Append("																																																																									   ");
            builder.Append("   table {																																																																							   ");
            builder.Append("    border-collapse: collapse !important;																																																															   ");
            builder.Append("  }																																																																								   ");
            builder.Append("																																																																									   ");
            builder.Append("  .headline {																																																																						   ");
            builder.Append("    color: #ffffff;																																																																				   ");
            builder.Append("    font-size: 36px;																																																																				   ");
            builder.Append("  }																																																																								   ");
            builder.Append("																																																																									   ");
            builder.Append(" .force-full-width {																																																																				   ");
            builder.Append("  width: 100% !important;																																																																			   ");
            builder.Append(" }																																																																									   ");
            builder.Append("																																																																									   ");
            builder.Append(" .force-width-80 {																																																																					   ");
            builder.Append("  width: 80% !important;																																																																			   ");
            builder.Append(" }																																																																									   ");
            builder.Append("																																																																									   ");
            builder.Append("																																																																									   ");
            builder.Append("																																																																									   ");
            builder.Append("																																																																									   ");
            builder.Append("  </style>																																																																							   ");
            builder.Append("																																																																									   ");
            builder.Append("  <style type=\"text/css\" media =\"screen\">																																																															   ");
            builder.Append("      @media screen {																																																																				   ");
            builder.Append("         /*Thanks Outlook 2013! http://goo.gl/XLxpyl*/																																																												   ");
            builder.Append("        td, h1, h2, h3 {																																																																			   ");
            builder.Append("          font-family: 'Droid Sans', 'Helvetica Neue', 'Arial', 'sans-serif' !important;																																																			   ");
            builder.Append("        }																																																																							   ");
            builder.Append("      }																																																																							   ");
            builder.Append("  </style>																																																																							   ");
            builder.Append("																																																																									   ");
            builder.Append("  <style type=\"text/css\" media =\"only screen and (max-width: 480px)\">																																																								   ");
            builder.Append("    /* Mobile styles */																																																																			   ");
            builder.Append("    @media only screen and (max-width: 480px) {																																																													   ");
            builder.Append("																																																																									   ");
            builder.Append("      table[class=\"w320\"] {                ");
            builder.Append("        width: 320px !important;																																																																	   ");
            builder.Append("      }																																																																							   ");
            builder.Append("																																																																									   ");
            builder.Append("      td[class=\"mobile-block\"] {                    ");
            builder.Append("        width: 100% !important;																																																																	   ");
            builder.Append("        display: block !important;																																																																	   ");
            builder.Append("      }																																																																							   ");
            builder.Append("																																																																									   ");
            builder.Append("																																																																									   ");
            builder.Append("    }																																																																								   ");
            builder.Append("  </style>																																																																							   ");
            builder.Append("</head>																																																																							   ");
            builder.Append("<body class=\"body\" style =\"padding:0; margin:0; display:block; background:#ffffff; -webkit-text-size-adjust:none\" bgcolor =\"#ffffff\">																																								   ");
            builder.Append("<table align=\"center\" cellpadding =\"0\" cellspacing =\"0\" class=\"force-full-width\" height=\"100%\" > ");
            builder.Append("  <tr>																																																																								   ");
            builder.Append("    <td align=\"center\" valign =\"top\" bgcolor =\"#ffffff\"  width =\"100%\">																																																								   ");
            builder.Append("      <center>																																																																						   ");
            builder.Append("        <table style=\"margin: 0 auto;\" cellpadding =\"0\" cellspacing=\"0\" width=\"600\" class=\"w320\">																																																	   ");
            builder.Append("          <tr>																																																																						   ");
            builder.Append("            <td align=\"center\" valign =\"top\">																																																														   ");
            builder.Append("																																																																									   ");
            builder.Append("                <table style=\"margin: 0 auto;\" cellpadding =\"0\" cellspacing=\"0\" class=\"force-full-width\" style =\"margin:0 auto;\">																																									   ");
            builder.Append("                  <tr>																																																																				   ");
            builder.Append("                    <td style=\"font-size: 30px; text-align:center;\">																																																								   ");
            builder.Append("                      <br>																																																																			   ");
            builder.Append("                        HHK Motorcycles!																																																																	   ");
            builder.Append("                      <br>																																																																			   ");
            builder.Append("                      <br>																																																																			   ");
            builder.Append("                    </td>																																																																			   ");
            builder.Append("                  </tr>																																																																			   ");
            builder.Append("                </table>																																																																			   ");
            builder.Append("																																																																									   ");
            builder.Append("                <table style=\"margin: 0 auto;\" cellpadding =\"0\" cellspacing=\"0\" class=\"force-full-width\" bgcolor =\"#4dbfbf\">																																											   ");
            builder.Append("                  <tr>																																																																				   ");
            builder.Append("                    <td>																																																																			   ");
            builder.Append("                    <br>																																																																			   ");
            builder.Append("                      <img src=\"https://www.filepicker.io/api/file/TjmeNWS5Q2SFmtJlUGLf \" width =\"224\" height =\"240\" alt=\"robot picture\">																																								   ");
            builder.Append("                    </td>																																																																			   ");
            builder.Append("                  </tr>																																																																			   ");
            builder.Append("                  <tr>																																																																				   ");
            builder.Append("                    <td class=\"headline\">																																																															   ");
            builder.Append("                      Tú factura está lista!																																																														   ");
            builder.Append("                    </td>																																																																			   ");
            builder.Append("                  </tr>																																																																			   ");
            builder.Append("                  <tr>																																																																				   ");
            builder.Append("                    <td>																																																																			   ");
            builder.Append("                    </td>																																																																			   ");
            builder.Append("                  </tr>																																																																			   ");
            builder.Append("                  <tr>																																																																				   ");
            builder.Append("                    <td>																																																																			   ");
            builder.Append("                      <br>																																																																			  ");
            builder.Append("                    </td>																																																																			  ");
            builder.Append("                  </tr>																																																																			  ");
            builder.Append("                </table>																																																																			  ");
            builder.Append("																																																																									  ");
            builder.Append("                <table style=\"margin: 0 auto;\" cellpadding =\"0\" cellspacing=\"0\" class=\"force-full-width\" bgcolor =\"#f5774e\">																																											  ");
            builder.Append("                  <tr>																																																																				  ");
            builder.Append("                    <td style=\"background-color:#f5774e;\">																																																											  ");
            builder.Append("																																																																									  ");
            builder.Append("                    <center>																																																																		  ");
            builder.Append("                      <table style=\"margin:0 auto;\" cellspacing =\"0\" cellpadding=\"0\" class=\"force-width-80\">																																														  ");
            builder.Append("                        <tr>																																																																		  ");
            builder.Append("                          <td style=\"text-align:left; color:#933f24\">																																																								  ");
            builder.Append("                          <br>																																																																		  ");
            builder.Append("                          <br>																																																																		  ");
            builder.Append("                            <span style=\"color:#ffffff;\">" + cliente.Nombre + " " + cliente.PrimerApellido + "</span> <br>																																																					  ");
            builder.Append("                            " + cliente.Direccion + " <br>																																																													  ");
            builder.Append("                            " + cliente.Telefono + "	<br>																																																														  ");
            builder.Append("                          </td>																																																																	  ");
            builder.Append("                          <td style=\"text-align:right; vertical-align:top; color:#933f24\">																																																			  ");
            builder.Append("                          <br>																																																																		  ");
            builder.Append("                          <br>																																																																		  ");
            builder.Append("                            <span style=\"color:#ffffff;\">Factura</span> <br>																																																				  ");
            builder.Append("                            " + venta.Fecha.ToString() + "																																																															  ");
            builder.Append("                          </td>																																																																	  ");
            builder.Append("                        </tr>																																																																		  ");
            builder.Append("                      </table>																																																																		  ");
            builder.Append("																																																																									  ");
            builder.Append("																																																																									  ");
            foreach (var item in carrito)
            {
                builder.Append("                      <table style=\"margin:0 auto;\" cellspacing =\"0\" cellpadding=\"0\" class=\"force-width-80\">																																														  ");
                builder.Append("                        <tr>																																																																		  ");
                builder.Append("                          <td  class=\"mobile-block\" > ");
                builder.Append("                          <br>																																																																		  ");
                builder.Append("                          <br>																																																																		  ");
                builder.Append("																																																																									  ");
                builder.Append("                            <table cellspacing=\"0\" cellpadding=\"0\" class=\"force-full-width\">																																																		  ");
                builder.Append("                              <tr>																																																																	  ");
                builder.Append("                                <td style=\"color:#ffffff; background-color:#ac4d2f; padding: 10px 0px;\">																																															  ");
                builder.Append("                                  Artículo																																																																  ");
                builder.Append("                                </td>																																																																  ");
                builder.Append("                              </tr>																																																																  ");
                builder.Append("                              <tr>																																																																	  ");
                builder.Append("                                <td style=\"color:#933f24; padding:10px 0px; background-color: #f7a084;\">																																															  ");
                builder.Append("                                  " + item.Productos.Nombre + "																																																														  ");
                builder.Append("                                </td>																																																																  ");
                builder.Append("                              </tr>																																																																  ");
                builder.Append("                            </table>																																																																  ");
                builder.Append("                          </td>																																																																	  ");
                builder.Append("                          <td  class=\"mobile-block\">																																																												  ");
                builder.Append("                          <br>																																																																		  ");
                builder.Append("                          <br>																																																																		  ");
                builder.Append("																																																																									  ");
                builder.Append("                            <table cellspacing=\"0\" cellpadding=\"0\" class=\"force-full-width\">																																																		  ");
                builder.Append("                              <tr>																																																																	  ");
                builder.Append("                                <td style=\"color:#ffffff; background-color:#ac4d2f; padding: 10px 0px;\">																																															  ");
                builder.Append("                                Cantidad																																																																  ");
                builder.Append("                                </td>																																																																  ");
                builder.Append("                              </tr>																																																																  ");
                builder.Append("                              <tr>																																																																	  ");
                builder.Append("                                <td style=\"color:#933f24; padding:10px 0px; background-color: #f7a084;\">																																															  ");
                builder.Append("                                 " + item.Cantidad + "																																																															  ");
                builder.Append("                                </td>																																																																  ");
                builder.Append("                              </tr>																																																																  ");
                builder.Append("                            </table>																																																																  ");
                builder.Append("                          </td>																																																																	  ");
                builder.Append("                          <td class=\"mobile-block\">																																																												  ");
                builder.Append("                          <br>																																																																		  ");
                builder.Append("                          <br>																																																																		  ");
                builder.Append("																																																																									  ");
                builder.Append("                            <table cellspacing=\"0\" cellpadding=\"0\" class=\"force-full-width\">																																																		  ");
                builder.Append("                              <tr>																																																																	  ");
                builder.Append("                                <td style=\"color:#ffffff; background-color:#ac4d2f; padding: 10px 0px;\">																																															  ");
                builder.Append("                                  Costo Total																																																															  ");
                builder.Append("                                </td>																																																																  ");
                builder.Append("                              </tr>																																																																  ");
                builder.Append("                              <tr>																																																																	  ");
                builder.Append("                                <td style=\"color:#933f24; padding:10px 0px; background-color: #f7a084;\">																																															  ");
                builder.Append("                                 " + item.Costo + "																																																															  ");
                builder.Append("                                </td>																																																																  ");
                builder.Append("                              </tr>																																																																  ");
                builder.Append("                            </table>																																																																  ");
                builder.Append("                          </td>																																																																	  ");
                builder.Append("                        </tr>																																																																		  ");
                builder.Append("                      </table>																																																																		  ");
            }
            builder.Append("																																																																									  ");
            builder.Append("																																																																									  ");
            builder.Append("                      <table  style=\"margin: 0 auto;\" cellspacing =\"0\" cellpadding=\"0\" class=\"force-width-80\">																																														  ");
            builder.Append("                        <tr>																																																																		  ");
            builder.Append("                          <td style=\"color:#933f24; text-align:left; border-bottom:1px solid #933f24;\">																																															  ");
            builder.Append("                          <br>																																																																		  ");
            builder.Append("                          <br>																																																																		  ");
            builder.Append("                            El total de la venta es " + venta.Total + " MXN, y ha sido cargado a su tarjeta de crédito.																																														  ");
            builder.Append("                            <br>																																																																	  ");
            builder.Append("                            <br>																																																																	  ");
            builder.Append("                          </td>																																																																	  ");
            builder.Append("                        </tr>																																																																		  ");
            builder.Append("                      </table>																																																																		  ");
            builder.Append("																																																																									  ");
            builder.Append("																																																																									  ");
            builder.Append("                      <table style=\"margin: 0 auto;\" cellspacing =\"0\" cellpadding=\"0\" class=\"force-width-80\">																																														  ");
            builder.Append("                        <tr>																																																																		  ");
            builder.Append("                          <td style=\"text-align:left; color:#933f24;\">																																																								  ");
            builder.Append("                          <br>																																																																		  ");
            builder.Append("                            Gracias por su compra.																																	  ");
            builder.Append("                          <br>																																																																		  ");
            builder.Append("                          <br>																																																																		  ");
            builder.Append("                          HHK Motorcycles.																																																																  ");
            builder.Append("                          <br>																																																																		  ");
            builder.Append("                          <br>																																																																		  ");
            builder.Append("                          <br>																																																																		  ");
            builder.Append("                          </td>																																																																	  ");
            builder.Append("                        </tr>																																																																		  ");
            builder.Append("                      </table>																																																																		  ");
            builder.Append("                    </center>																																																																		  ");
            builder.Append("                    </td>																																																																			  ");
            builder.Append("                  </tr>																																																																			  ");
            builder.Append("																																																																									  ");
            builder.Append("																																																																									  ");
            builder.Append("                </table>																																																																			  ");
            builder.Append("																																																																									  ");
            builder.Append("                <table style=\"margin: 0 auto;\" cellpadding =\"0\" cellspacing=\"0\" class=\"force-full-width\" bgcolor =\"#414141\" style=\"margin: 0 auto\">																																					  ");
            builder.Append("                  <tr>																																																																				  ");
            builder.Append("                    <td style=\"background-color:#414141;\">																																																											  ");
            builder.Append("                    <br>																																																																			  ");
            builder.Append("                    <br>																																																																			  ");
            builder.Append("                      <img src=\"https://www.filepicker.io/api/file/R4VBTe2UQeGdAlM7KDc4 \" alt =\"google+\">																																															  ");
            builder.Append("                      <img src=\"https://www.filepicker.io/api/file/cvmSPOdlRaWQZnKFnBGt \" alt =\"facebook\">																																															  ");
            builder.Append("                      <img src=\"https://www.filepicker.io/api/file/Gvu32apSQDqLMb40pvYe \" alt =\"twitter\">																																															  ");
            builder.Append("                      <br>																																																																			  ");
            builder.Append("                      <br>																																																																			  ");
            builder.Append("                    </td>																																																																			  ");
            builder.Append("                  </tr>																																																																			  ");
            builder.Append("                  <tr>																																																																				  ");
            builder.Append("                    <td style=\"color:#bbbbbb; font-size:12px;\">																																																									  ");
            builder.Append("                       © 2019 Antonio Contreras Universidad UCAD																																																													  ");
            builder.Append("                       <br>																																																																		  ");
            builder.Append("                       <br>																																																																		  ");
            builder.Append("                    </td>																																																																			  ");
            builder.Append("                  </tr>																																																																			  ");
            builder.Append("                </table>																																																																			  ");
            builder.Append("            </td>																																																																					  ");
            builder.Append("          </tr>																																																																					  ");
            builder.Append("        </table>																																																																					  ");
            builder.Append("    </center>																																																																						  ");
            builder.Append("    </td>																																																																							  ");
            builder.Append("  </tr>																																																																							  ");
            builder.Append("</table>																																																																							  ");
            builder.Append("</body>																																																																							  ");
            builder.Append("</html>																																																																							  ");
            var validar = builder.ToString();
            return builder.ToString();
        }
    }
}