//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograWebHHK
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarritoCompras
    {
        public int IdCarrito { get; set; }
        public int IdCliente { get; set; }
        public int Sku { get; set; }
        public int Cantidad { get; set; }
        public decimal Costo { get; set; }
        public int IdMp { get; set; }
        public bool Ventido { get; set; }
        public bool estaActivo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ModoPago ModoPago { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
