//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograWebHHK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public int IdDetalle { get; set; }
        public Nullable<int> NumeroDetalle { get; set; }
        public int IdVenta { get; set; }
        public int Sku { get; set; }
        public decimal Costo { get; set; }
        public decimal Total { get; set; }
        public int Cantidad { get; set; }
    }
}
