//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograWebHHK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.CarritoCompras = new HashSet<CarritoCompras>();
        }
    
        public int Sku { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionSecundaria { get; set; }
        public int IdDepartamento { get; set; }
        public string RutaImagen { get; set; }
        public double Costo { get; set; }
        public Nullable<int> Inventario { get; set; }
        public bool estaActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarritoCompras> CarritoCompras { get; set; }
        public virtual Departamento Departamento { get; set; }
    }
}
