//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPrograWebHHK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int IdVenta { get; set; }
        public int IdCliente { get; set; }
        public int IdMp { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal subtotal { get; set; }
        public decimal Total { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ModoPago ModoPago { get; set; }
    }
}
